### ISSUE TITLE
Add shortcuts to save and load

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm-in/webmark#13]
https://developer.chrome.com/extensions/commands#usage

**Comment by Bartleby2718** [comment]
This issue wasn't solved in the commit. Must have deleted the code when I made a commit.

**Comment by Bartleby2718** [comment]
### Memo
https://itnext.io/create-chrome-extension-with-reactjs-using-inject-page-strategy-137650de1f39
3. Injecting a React app to page as content script
- `npm run eject` -> make a commit here once
- `npm install`
- In `webpack.config.js`: (https://github.com/satendra02/react-chrome-extension/issues/2)
  - Change `entry` and `output`
  - Set `runtimeChunk: false,`
  - Remove `.[contenthash:8]` and `[chunkhash:8]` here and there
- Update `manifest.json`

**Comment by Bartleby2718** [comment]
```
"background": {
    "scripts": ["background.js"],
    "persistent": false
  },
```
```
chrome.commands.onCommand.addListener(function (command) {
    if (command = 'save') {
        saveClicked();
    }
    else if (command = 'load') {
        loadClicked();
    }
});
```

**Comment by Bartleby2718** [comment]
Test on Macs before releasing.

**Comment by jeongm-in** [comment]
@jeongm-in
