### ISSUE TITLE
Remove unnecessary files

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm-in/webmark#2]
I haven't understood the entire React+TypeScript project structure, so I kept all the files. Remove any and all files that aren't necessary.

**Comment by jeongm-in** [comment]
- Remove ico files
- Remove App

**Comment by Bartleby2718** [comment]
- `index.css`, `serviceWorker.ts` (Delete the comments in `index.tsx`)
- (`react-app-env.d.ts` is re-generated by `react-scripts build`.)

**Comment by jeongm-in** [comment]
Remove github icon. No longer needed due to fontawesome integration.
Also change default_icon in manifest.json as well
