### ISSUE TITLE
index.tsx 'chrome is not defined'

### ISSUE THREAD

**Issue by jeongm-in** [jeongm-in/webmark#20]
even after `npm install`, the program could not find `chrome` as it was not defined anywhere.
Need `/*global chrome*/` at the beginning of index.tsx.

**Comment by Bartleby2718** [comment]
You forgot to mention the issue ID from the commit.
Here's the commit: https://github.com/jeongm-in/webmark/commit/4825b7ce12ee3de271613f6807b39c8010e0d564.
