### ISSUE TITLE
Find better type guard structure for `string|undefined` variable types.

### ISSUE THREAD

**Issue by jeongm-in** [jeongm-in/webmark#25]
In `typeCheckString()` function, currently type guard returns `"https://example.com/error"` if variable type is undefined.

**Comment by Bartleby2718** [comment]
Note: This was moved to `getCurrentdSave` in https://github.com/jeongm-in/webmark/commit/82a73a4772e328e7fdc96f00a68feaba4f514997

**Comment by Bartleby2718** [comment]
Also, using `? ` may be better than declaring it `string | undefined`. https://stackoverflow.com/questions/37632760/what-is-the-question-mark-for-in-a-typescript-parameter-name

**Comment by jeongm-in** [comment]
why should we put the url and title as optional parameters? These are required to register as bookmarks. 
Also, changing url and title parameters as optional still does not solve the problem of type guarding `string|undefined`.
