### ISSUE TITLE
No check for existence of folder with saved folder ID

### ISSUE THREAD

**Issue by jeongm-in** [jeongm-in/webmark#26]
`saveToWebmarkFolder()` function checks `chrome.storage.sync` to see if key 'webmarkFolderId' exists and retrieves value folder ID. However, if folder is removed, extension will crash because it cannot access folder using folder ID fetched from `chrome.storage.sync`. Also need to check if folder with saved folder ID exists.

**Comment by Bartleby2718** [comment]
Good one 👍

**Comment by Bartleby2718** [comment]
The same applies to `loadClicked()`; it checks whether `webmarkFolderId` is in the storage but not whether if there is an actual folder with that `id`.
