### ISSUE TITLE
Refactor buttons

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm-in/webmark#3]

**Comment by jeongm-in** [comment]
Yes, we should talk about this. React recommends inline styling (`style=" "`), or put every style in json object and then load it within the Javascript files. I read from some article that the traditional way of linking to css file is not the best way to do styles in React, but I think that is just the author's opinion. Anyways, there are three ways to do styles, and I think JSON object method is the preferable in terms of scalability and modularity. What are your thoughts?

**Comment by Bartleby2718** [comment]
Discussed on Slack. Deleted my original issue description which discusses using CSS.
Decision: We will do everything with React.
