### ISSUE TITLE
Reformat code

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm-in/webmark#30]
I suggest that we set "editor.formatOnSave" to true in VS Code settings: https://stackoverflow.com/a/43248309/4370146

**Comment by jeongm-in** [comment]
I add this to settings.json, right?

**Comment by Bartleby2718** [comment]
Isn't easier to use the GUI?
gear button on the bottom left -> settings -> type `formatOnSave` -> check the checkbox

**Comment by Bartleby2718** [comment]
Anyway I think you're right.
