### ISSUE TITLE
Search for duplicates only within webmark folder

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm-in/webmark#49]
Edit: Replace [`chrome.bookmarks.search()`](https://developer.chrome.com/extensions/bookmarks#method-search) with [`chrome.bookmarks.getSubTree()`](https://developer.chrome.com/extensions/bookmarks#method-getSubTree)

**Comment by jeongm-in** [comment]
At least for loadRandom, we `getSubtree` directly from the directory with WebMarkId. So it doesn't escape the root of the subtree, which is the WebMark Folder. 
Is this issue targeting `search` function?

**Comment by Bartleby2718** [comment]
@jeongm-in Sorry, the title was ambiguous. Yes, I was indeed referring to `chrome.bookmarks.search()`.

**Comment by Bartleby2718** [comment]
+some refactorings
