### ISSUE TITLE
Change popup width and use ButtonGroup

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm-in/webmark#55]
I wish it could be flexible as long as it fits in one line, but I can't figure out how...

**Comment by jeongm-in** [comment]
probably could put a slider in the options page?

**Comment by Bartleby2718** [comment]
`'white-space': 'nowrap'`: https://stackoverflow.com/questions/19284153/how-to-get-a-responsive-button-in-bootstrap-3
`as React.CSSProperties`: https://stackoverflow.com/questions/52005083/how-to-define-css-variables-in-style-attribute-in-react-and-typescript
