### ISSUE TITLE
Remove unnecessary rule from webpack.config.js

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm-in/webmark#75]
Remove the following from `webpack.config.js`
```
        {
          test: /\.(js|mjs|jsx|ts|tsx)$/,
          include: path.resolve(__dirname, 'node_modules'),
          loader: require.resolve('babel-loader'),
        },
```
and the build time is shortened by 800ms!

**Comment by Bartleby2718** [comment]
@jeongm-in After a few re-builds, it seems like we can safely delete `include: /node_modules/,` from 
```
      {
        // Preprocess 3rd party .css files located in node_modules
        test: /\.css$/,
        include: /node_modules/,
        use: ['style-loader', 'css-loader'],
      }
```
It does not affect the build time significantly, but it'll look more concise once we remove it. What do you think about deleting the `include` line?

**Comment by jeongm-in** [comment]
Just tried, all third party styles work as before. 
Will remove this line.
