### ISSUE TITLE
Use popup.html for the popup

### ISSUE THREAD

**Issue by Bartleby2718** [jeongm-in/webmark#81]
https://developer.chrome.com/extensions/samples
Seems like that's the naming convention.
However, `react-scripts build` requires an `index.html` so can't delete that.

**Comment by jeongm-in** [comment]
Is this necessary?

**Comment by Bartleby2718** [comment]
@jeongm-in Functionally no, but I like adhering to the conventions.

**Comment by Bartleby2718** [comment]
Hmm, if we do this, we need `popup.js` for `popup.html`...

**Comment by jeongm-in** [comment]
Surely we could do so with webpack, but... the url `popup.html` isn't even exposed anyways.

**Comment by Bartleby2718** [comment]
Yeah, let's put this on hold until we eject out of CRA.
