### ISSUE TITLE
Refactor and edit typos for options related files

### ISSUE THREAD

**Issue by jeongm-in** [jeongm-in/webmark#86]

**Comment by Bartleby2718** [comment]
![image](https://user-images.githubusercontent.com/7676354/60948810-c0348000-a32e-11e9-86ce-0cd24bbeeb27.png)
If this--body not filling up 100% of the html--is the issue, it can be solved with `height: 100vh`
![image](https://user-images.githubusercontent.com/7676354/60948877-e78b4d00-a32e-11e9-9474-729dc4f92227.png)
But I did see that setting background color is enough to fill the entire page, so I'm just leaving this as a note.

**Comment by jeongm-in** [comment]
I tried 100vh option. If the card gets longer, it will not display everything correctly.
