### ISSUE TITLE
Fix shortcuts not working 

### ISSUE THREAD

**Issue by jeongm-in** [jeongm-in/webmark#87]
All of sudden, shortcuts is not working. 
Thought #75 might be the culprit, but even after reverting the changes did not work.

**Comment by Bartleby2718** [comment]
Did `git pull`, `npm install`, `npm run build`, and shortcuts are fine in my laptop. Can't replicate this issue.

**Comment by Bartleby2718** [comment]
@jeongm-in Is it still not working?

**Comment by jeongm-in** [comment]
works fine on different setup. I will try again tonight on that machine. Closing the issue
