### ISSUE TITLE
Change permission of tab to activeTab

### ISSUE THREAD

**Issue by jeongm-in** [jeongm-in/webmark#88]
https://developer.chrome.com/extensions/activeTab
we do not need `tab` permission, and with current WebMark features `activeTab` is all we need. 
Tested with `activeTab` permission and all works as expected.

**Comment by Bartleby2718** [comment]
🆗 
> You can use most chrome.tabs methods and events without declaring any permissions in the extension's manifest file.
https://developer.chrome.com/extensions/tabs

**Comment by jeongm-in** [comment]
So remove tab permission entirely then?

**Comment by Bartleby2718** [comment]
I'm saying it's okay to change from `tab` to `activeTab`.

**Comment by jeongm-in** [comment]
:ok:
